-- Seed Data for PalabraBox Phase 3.5
INSERT INTO public.scenarios (id, title, title_display, language, level, description, emoji, category, sort_order) VALUES
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'Colors & Shapes', 'Colores y Formas', 'english', 'beginner', 'Learn the primary colors and basic shapes in English.', '🎨', 'colors', 1),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'Animals', 'Los Animales', 'english', 'beginner', 'Learn the names of common animals in English.', '🐶', 'animals', 2),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'Food & Drinks', 'Comida y Bebidas', 'english', 'beginner', 'Essential vocabulary for eating and drinking.', '🍔', 'food', 3),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'Family', 'La Familia', 'english', 'beginner', 'Vocabulary related to family members.', '👨‍👩‍👧‍👦', 'family', 4),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'Parts of the Body', 'Partes del Cuerpo', 'english', 'intermediate', 'Learn how to name body parts in English.', '🦵', 'body', 5),
('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'Travel & Transport', 'Viajes y Transporte', 'english', 'intermediate', 'Useful words for traveling and transportation.', '✈️', 'travel', 6),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'Los Colores y Formas', 'Colors & Shapes', 'spanish', 'beginner', 'Learn the primary colors and basic shapes in Spanish.', '🎨', 'colors', 1),
('3a2ecbbd-0112-4c22-bde1-f8e136cf95fc', 'Los Animales', 'Animals', 'spanish', 'beginner', 'Aprende los nombres de los animales más comunes en español.', '🐶', 'animals', 2),
('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'Comida y Bebidas', 'Food & Drinks', 'spanish', 'beginner', 'Essential vocabulary for eating and drinking in Spanish.', '🍔', 'food', 3),
('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a', 'Mi Familia', 'My Family', 'spanish', 'beginner', 'Vocabulary related to family members in Spanish.', '👨‍👩‍👧‍👦', 'family', 4),
('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'Partes del Cuerpo', 'Body Parts', 'spanish', 'intermediate', 'Learn how to name body parts in Spanish.', '🦵', 'body', 5),
('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c', 'Viajes y Transporte', 'Travel', 'spanish', 'intermediate', 'Useful words for traveling and transportation in Spanish.', '✈️', 'travel', 6)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.words (word, language, level, category, translation_es, translation_en, image_emoji, audio_text) VALUES
('red', 'english', 'beginner', 'colors', 'rojo', NULL, '🔴', 'red'),
('blue', 'english', 'beginner', 'colors', 'azul', NULL, '🔵', 'blue'),
('yellow', 'english', 'beginner', 'colors', 'amarillo', NULL, '🟡', 'yellow'),
('green', 'english', 'beginner', 'colors', 'verde', NULL, '🟢', 'green'),
('black', 'english', 'beginner', 'colors', 'negro', NULL, '⚫', 'black'),
('white', 'english', 'beginner', 'colors', 'blanco', NULL, '⚪', 'white'),
('purple', 'english', 'beginner', 'colors', 'morado', NULL, '🟣', 'purple'),
('orange', 'english', 'beginner', 'colors', 'naranja', NULL, '🟠', 'orange'),
('dog', 'english', 'beginner', 'animals', 'perro', NULL, '🐶', 'dog'),
('cat', 'english', 'beginner', 'animals', 'gato', NULL, '🐱', 'cat'),
('bird', 'english', 'beginner', 'animals', 'pájaro', NULL, '🐦', 'bird'),
('fish', 'english', 'beginner', 'animals', 'pez', NULL, '🐟', 'fish'),
('cow', 'english', 'beginner', 'animals', 'vaca', NULL, '🐄', 'cow'),
('horse', 'english', 'beginner', 'animals', 'caballo', NULL, '🐴', 'horse'),
('pig', 'english', 'beginner', 'animals', 'cerdo', NULL, '🐷', 'pig'),
('rabbit', 'english', 'beginner', 'animals', 'conejo', NULL, '🐰', 'rabbit'),
('apple', 'english', 'beginner', 'food', 'manzana', NULL, '🍎', 'apple'),
('bread', 'english', 'beginner', 'food', 'pan', NULL, '🍞', 'bread'),
('water', 'english', 'beginner', 'food', 'agua', NULL, '💧', 'water'),
('milk', 'english', 'beginner', 'food', 'leche', NULL, '🥛', 'milk'),
('cheese', 'english', 'beginner', 'food', 'queso', NULL, '🧀', 'cheese'),
('egg', 'english', 'beginner', 'food', 'huevo', NULL, '🥚', 'egg'),
('meat', 'english', 'beginner', 'food', 'carne', NULL, '🥩', 'meat'),
('chicken', 'english', 'beginner', 'food', 'pollo', NULL, '🍗', 'chicken'),
('mother', 'english', 'beginner', 'family', 'madre', NULL, '👩', 'mother'),
('father', 'english', 'beginner', 'family', 'padre', NULL, '👨', 'father'),
('brother', 'english', 'beginner', 'family', 'hermano', NULL, '👦', 'brother'),
('sister', 'english', 'beginner', 'family', 'hermana', NULL, '👧', 'sister'),
('grandmother', 'english', 'beginner', 'family', 'abuela', NULL, '👵', 'grandmother'),
('grandfather', 'english', 'beginner', 'family', 'abuelo', NULL, '👴', 'grandfather'),
('aunt', 'english', 'beginner', 'family', 'tía', NULL, '👱‍♀️', 'aunt'),
('uncle', 'english', 'beginner', 'family', 'tío', NULL, '👱‍♂️', 'uncle'),
('head', 'english', 'intermediate', 'body', 'cabeza', NULL, '🗣️', 'head'),
('hand', 'english', 'intermediate', 'body', 'mano', NULL, '✋', 'hand'),
('leg', 'english', 'intermediate', 'body', 'pierna', NULL, '🦵', 'leg'),
('foot', 'english', 'intermediate', 'body', 'pie', NULL, '🦶', 'foot'),
('eye', 'english', 'intermediate', 'body', 'ojo', NULL, '👁️', 'eye'),
('ear', 'english', 'intermediate', 'body', 'oreja', NULL, '👂', 'ear'),
('mouth', 'english', 'intermediate', 'body', 'boca', NULL, '👄', 'mouth'),
('nose', 'english', 'intermediate', 'body', 'nariz', NULL, '👃', 'nose'),
('car', 'english', 'intermediate', 'travel', 'coche', NULL, '🚗', 'car'),
('bus', 'english', 'intermediate', 'travel', 'autobús', NULL, '🚌', 'bus'),
('train', 'english', 'intermediate', 'travel', 'tren', NULL, '🚆', 'train'),
('plane', 'english', 'intermediate', 'travel', 'avión', NULL, '✈️', 'plane'),
('ticket', 'english', 'intermediate', 'travel', 'billete', NULL, '🎫', 'ticket'),
('hotel', 'english', 'intermediate', 'travel', 'hotel', NULL, '🏨', 'hotel'),
('passport', 'english', 'intermediate', 'travel', 'pasaporte', NULL, '🛂', 'passport'),
('airport', 'english', 'intermediate', 'travel', 'aeropuerto', NULL, '🛫', 'airport'),
('rojo', 'spanish', 'beginner', 'colors', NULL, 'red', '🔴', 'rojo'),
('azul', 'spanish', 'beginner', 'colors', NULL, 'blue', '🔵', 'azul'),
('amarillo', 'spanish', 'beginner', 'colors', NULL, 'yellow', '🟡', 'amarillo'),
('verde', 'spanish', 'beginner', 'colors', NULL, 'green', '🟢', 'verde'),
('negro', 'spanish', 'beginner', 'colors', NULL, 'black', '⚫', 'negro'),
('blanco', 'spanish', 'beginner', 'colors', NULL, 'white', '⚪', 'blanco'),
('morado', 'spanish', 'beginner', 'colors', NULL, 'purple', '🟣', 'morado'),
('naranja', 'spanish', 'beginner', 'colors', NULL, 'orange', '🟠', 'naranja'),
('perro', 'spanish', 'beginner', 'animals', NULL, 'dog', '🐶', 'perro'),
('gato', 'spanish', 'beginner', 'animals', NULL, 'cat', '🐱', 'gato'),
('pájaro', 'spanish', 'beginner', 'animals', NULL, 'bird', '🐦', 'pájaro'),
('pez', 'spanish', 'beginner', 'animals', NULL, 'fish', '🐟', 'pez'),
('vaca', 'spanish', 'beginner', 'animals', NULL, 'cow', '🐄', 'vaca'),
('caballo', 'spanish', 'beginner', 'animals', NULL, 'horse', '🐴', 'caballo'),
('cerdo', 'spanish', 'beginner', 'animals', NULL, 'pig', '🐷', 'cerdo'),
('conejo', 'spanish', 'beginner', 'animals', NULL, 'rabbit', '🐰', 'conejo'),
('manzana', 'spanish', 'beginner', 'food', NULL, 'apple', '🍎', 'manzana'),
('pan', 'spanish', 'beginner', 'food', NULL, 'bread', '🍞', 'pan'),
('agua', 'spanish', 'beginner', 'food', NULL, 'water', '💧', 'agua'),
('leche', 'spanish', 'beginner', 'food', NULL, 'milk', '🥛', 'leche'),
('queso', 'spanish', 'beginner', 'food', NULL, 'cheese', '🧀', 'queso'),
('huevo', 'spanish', 'beginner', 'food', NULL, 'egg', '🥚', 'huevo'),
('carne', 'spanish', 'beginner', 'food', NULL, 'meat', '🥩', 'carne'),
('pollo', 'spanish', 'beginner', 'food', NULL, 'chicken', '🍗', 'pollo'),
('madre', 'spanish', 'beginner', 'family', NULL, 'mother', '👩', 'madre'),
('padre', 'spanish', 'beginner', 'family', NULL, 'father', '👨', 'padre'),
('hermano', 'spanish', 'beginner', 'family', NULL, 'brother', '👦', 'hermano'),
('hermana', 'spanish', 'beginner', 'family', NULL, 'sister', '👧', 'hermana'),
('abuela', 'spanish', 'beginner', 'family', NULL, 'grandmother', '👵', 'abuela'),
('abuelo', 'spanish', 'beginner', 'family', NULL, 'grandfather', '👴', 'abuelo'),
('tía', 'spanish', 'beginner', 'family', NULL, 'aunt', '👱‍♀️', 'tía'),
('tío', 'spanish', 'beginner', 'family', NULL, 'uncle', '👱‍♂️', 'tío'),
('cabeza', 'spanish', 'intermediate', 'body', NULL, 'head', '🗣️', 'cabeza'),
('mano', 'spanish', 'intermediate', 'body', NULL, 'hand', '✋', 'mano'),
('pierna', 'spanish', 'intermediate', 'body', NULL, 'leg', '🦵', 'pierna'),
('pie', 'spanish', 'intermediate', 'body', NULL, 'foot', '🦶', 'pie'),
('ojo', 'spanish', 'intermediate', 'body', NULL, 'eye', '👁️', 'ojo'),
('oreja', 'spanish', 'intermediate', 'body', NULL, 'ear', '👂', 'oreja'),
('boca', 'spanish', 'intermediate', 'body', NULL, 'mouth', '👄', 'boca'),
('nariz', 'spanish', 'intermediate', 'body', NULL, 'nose', '👃', 'nariz'),
('coche', 'spanish', 'intermediate', 'travel', NULL, 'car', '🚗', 'coche'),
('autobús', 'spanish', 'intermediate', 'travel', NULL, 'bus', '🚌', 'autobús'),
('tren', 'spanish', 'intermediate', 'travel', NULL, 'train', '🚆', 'tren'),
('avión', 'spanish', 'intermediate', 'travel', NULL, 'plane', '✈️', 'avión'),
('billete', 'spanish', 'intermediate', 'travel', NULL, 'ticket', '🎫', 'billete'),
('hotel', 'spanish', 'intermediate', 'travel', NULL, 'hotel', '🏨', 'hotel'),
('pasaporte', 'spanish', 'intermediate', 'travel', NULL, 'passport', '🛂', 'pasaporte'),
('aeropuerto', 'spanish', 'intermediate', 'travel', NULL, 'airport', '🛫', 'aeropuerto');

INSERT INTO public.questions (scenario_id, type, question_text, question_text_tts, correct_answer, wrong_answers, image_emoji, hint, sort_order) VALUES
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'multiple_choice', '¿Cómo se dice "rojo" en inglés?', 'red', 'red', ARRAY['orange', 'green', 'purple'], NULL, NULL, 1),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'multiple_choice', '¿Cómo se dice "azul" en inglés?', 'blue', 'blue', ARRAY['red', 'white', 'black'], NULL, NULL, 2),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'multiple_choice', '¿Cómo se dice "verde" en inglés?', 'green', 'green', ARRAY['yellow', 'blue', 'orange'], NULL, NULL, 3),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'image_match', '¿Qué palabra representa 🔴?', 'red', 'red', ARRAY['yellow', 'orange', 'blue'], '🔴', NULL, 4),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'image_match', '¿Qué palabra representa 🔵?', 'blue', 'blue', ARRAY['purple', 'green', 'white'], '🔵', NULL, 5),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'listening', 'Escucha y selecciona la palabra correcta', 'yellow', 'yellow', ARRAY['black', 'orange', 'green'], NULL, NULL, 6),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'listening', 'Escucha y selecciona la palabra correcta', 'white', 'white', ARRAY['black', 'red', 'green'], NULL, NULL, 7),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'word_order', 'Ordena las palabras para formar: "El color es rojo"', 'the color is red', 'the color is red', ARRAY['sun', 'not', 'blue'], NULL, 'Translate to English', 8),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'word_order', 'Ordena las palabras para formar: "El cielo es azul"', 'the sky is blue', 'the sky is blue', ARRAY['green', 'are', 'bird'], NULL, 'Translate to English', 9),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'word_order', 'Ordena las palabras para formar: "La caja amarilla"', 'the yellow box', 'the yellow box', ARRAY['red', 'boxes', 'is'], NULL, 'Translate to English', 10),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'fill_blank', 'The color of a frog is ____.', 'green', 'green', ARRAY['red', 'blue', 'white'], NULL, NULL, 11),
('e11c8282-e565-4f40-8483-e0202e8d3eaa', 'fill_blank', 'The sun is ____.', 'yellow', 'yellow', ARRAY['purple', 'black', 'orange'], NULL, NULL, 12),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'multiple_choice', '¿Cómo se dice "perro" en inglés?', 'dog', 'dog', ARRAY['fish', 'cow', 'cat'], NULL, NULL, 13),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'image_match', '¿Qué palabra representa 🐱?', 'cat', 'cat', ARRAY['horse', 'fish', 'rabbit'], '🐱', NULL, 14),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'listening', 'Escucha y selecciona la palabra correcta', 'pig', 'pig', ARRAY['bird', 'rabbit', 'dog'], NULL, NULL, 15),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'word_order', 'Ordena las palabras para formar: "El perro ladra"', 'the dog barks', 'the dog barks', ARRAY['cat', 'meows', 'is'], NULL, 'Translate to English', 16),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'word_order', 'Ordena las palabras para formar: "Un conejo rápido"', 'a fast rabbit', 'a fast rabbit', ARRAY['slow', 'turtle', 'the'], NULL, 'Translate to English', 17),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'word_order', 'Ordena las palabras para formar: "Mi gato duerme"', 'my cat sleeps', 'my cat sleeps', ARRAY['dog', 'playing', 'is'], NULL, 'Translate to English', 18),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'fill_blank', 'A ___ says meow.', 'cat', 'cat', ARRAY['dog', 'cow', 'fish'], NULL, NULL, 19),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'fill_blank', 'A ___ swims in the water.', 'fish', 'fish', ARRAY['bird', 'cat', 'horse'], NULL, NULL, 20),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'multiple_choice', '¿Cómo se dice "queso" en inglés?', 'cheese', 'cheese', ARRAY['bread', 'water', 'meat'], NULL, NULL, 21),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'image_match', '¿Qué palabra representa 🥛?', 'milk', 'milk', ARRAY['cheese', 'apple', 'meat'], '🥛', NULL, 22),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'listening', 'Escucha y selecciona la palabra correcta', 'cheese', 'cheese', ARRAY['milk', 'water', 'apple'], NULL, NULL, 23),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'word_order', 'Ordena las palabras para formar: "Yo bebo agua"', 'i drink water', 'i drink water', ARRAY['eat', 'milk', 'you'], NULL, 'Translate to English', 24),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'word_order', 'Ordena las palabras para formar: "Me gusta el pollo"', 'i like chicken', 'i like chicken', ARRAY['hate', 'fish', 'do'], NULL, 'Translate to English', 25),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'word_order', 'Ordena las palabras para formar: "Una manzana roja"', 'a red apple', 'a red apple', ARRAY['green', 'the', 'meat'], NULL, 'Translate to English', 26),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'fill_blank', 'I eat ___ with cheese.', 'bread', 'bread', ARRAY['water', 'milk', 'apple'], NULL, NULL, 27),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'fill_blank', 'Cows give us ___.', 'milk', 'milk', ARRAY['bread', 'chicken', 'apple'], NULL, NULL, 28),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'multiple_choice', '¿Cómo se dice "madre" en inglés?', 'mother', 'mother', ARRAY['brother', 'father', 'grandmother'], NULL, NULL, 29),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'image_match', '¿Qué palabra representa 👴?', 'grandfather', 'grandfather', ARRAY['aunt', 'brother', 'grandmother'], '👴', NULL, 30),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'listening', 'Escucha y selecciona la palabra correcta', 'brother', 'brother', ARRAY['mother', 'father', 'sister'], NULL, NULL, 31),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'word_order', 'Ordena las palabras para formar: "Mi hermano pequeño"', 'my little brother', 'my little brother', ARRAY['big', 'sister', 'is'], NULL, 'Translate to English', 32),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'word_order', 'Ordena las palabras para formar: "Ella es mi tía"', 'she is my aunt', 'she is my aunt', ARRAY['he', 'uncle', 'the'], NULL, 'Translate to English', 33),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'word_order', 'Ordena las palabras para formar: "Mi padre trabaja"', 'my father works', 'my father works', ARRAY['mother', 'sleeping', 'is'], NULL, 'Translate to English', 34),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'fill_blank', 'My mother and ___.', 'father', 'father', ARRAY['sister', 'uncle', 'aunt'], NULL, NULL, 35),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'multiple_choice', '¿Cómo se dice "cabeza" en inglés?', 'head', 'head', ARRAY['mouth', 'ear', 'eye'], NULL, NULL, 36),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'image_match', '¿Qué palabra representa 👁️?', 'eye', 'eye', ARRAY['ear', 'leg', 'head'], '👁️', NULL, 37),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'listening', 'Escucha y selecciona la palabra correcta', 'leg', 'leg', ARRAY['hand', 'foot', 'ear'], NULL, NULL, 38),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'word_order', 'Ordena las palabras para formar: "Cierra los ojos"', 'close your eyes', 'close your eyes', ARRAY['open', 'mouth', 'my'], NULL, 'Translate to English', 39),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'word_order', 'Ordena las palabras para formar: "Mis dos manos"', 'my two hands', 'my two hands', ARRAY['one', 'feet', 'the'], NULL, 'Translate to English', 40),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'word_order', 'Ordena las palabras para formar: "Tengo una nariz"', 'i have a nose', 'i have a nose', ARRAY['two', 'ears', 'has'], NULL, 'Translate to English', 41),
('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'multiple_choice', '¿Cómo se dice "hotel" en inglés?', 'hotel', 'hotel', ARRAY['plane', 'ticket', 'car'], NULL, NULL, 42),
('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'image_match', '¿Qué palabra representa 🚌?', 'bus', 'bus', ARRAY['train', 'passport', 'hotel'], '🚌', NULL, 43),
('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'listening', 'Escucha y selecciona la palabra correcta', 'car', 'car', ARRAY['airport', 'hotel', 'plane'], NULL, NULL, 44),
('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'word_order', 'Ordena las palabras para formar: "Dónde está el hotel"', 'where is the hotel', 'where is the hotel', ARRAY['who', 'airport', 'are'], NULL, 'Translate to English', 45),
('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'word_order', 'Ordena las palabras para formar: "Necesito un billete"', 'i need a ticket', 'i need a ticket', ARRAY['want', 'passport', 'the'], NULL, 'Translate to English', 46),
('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'word_order', 'Ordena las palabras para formar: "El tren rápido"', 'the fast train', 'the fast train', ARRAY['slow', 'bus', 'a'], NULL, 'Translate to English', 47),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'multiple_choice', 'How do you say "white" in Spanish?', 'blanco', 'blanco', ARRAY['morado', 'verde', 'naranja'], NULL, NULL, 48),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'multiple_choice', 'How do you say "blue" in Spanish?', 'azul', 'azul', ARRAY['naranja', 'blanco', 'verde'], NULL, NULL, 49),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'multiple_choice', 'How do you say "red" in Spanish?', 'rojo', 'rojo', ARRAY['naranja', 'blanco', 'morado'], NULL, NULL, 50),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'image_match', 'Which word represents 🟣?', 'morado', 'morado', ARRAY['rojo', 'negro', 'azul'], '🟣', NULL, 51),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'image_match', 'Which word represents 🟠?', 'naranja', 'naranja', ARRAY['verde', 'morado', 'negro'], '🟠', NULL, 52),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'listening', 'Listen and select the correct word', 'azul', 'azul', ARRAY['amarillo', 'rojo', 'verde'], NULL, NULL, 53),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'listening', 'Listen and select the correct word', 'blanco', 'blanco', ARRAY['naranja', 'rojo', 'negro'], NULL, NULL, 54),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'word_order', 'Translate to Spanish: "The color is red"', 'el color es rojo', 'el color es rojo', ARRAY['sol', 'no', 'azul'], NULL, 'Translate to Spanish', 55),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'word_order', 'Translate to Spanish: "The sky is blue"', 'el cielo es azul', 'el cielo es azul', ARRAY['verde', 'son', 'pájaro'], NULL, 'Translate to Spanish', 56),
('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'word_order', 'Translate to Spanish: "The yellow box"', 'la caja amarilla', 'la caja amarilla', ARRAY['rojo', 'cajas', 'es'], NULL, 'Translate to Spanish', 57),
('3a2ecbbd-0112-4c22-bde1-f8e136cf95fc', 'multiple_choice', 'How do you say "fish" in Spanish?', 'pez', 'pez', ARRAY['gato', 'vaca', 'cerdo'], NULL, NULL, 58),
('3a2ecbbd-0112-4c22-bde1-f8e136cf95fc', 'image_match', 'Which word represents 🐷?', 'cerdo', 'cerdo', ARRAY['pájaro', 'conejo', 'pez'], '🐷', NULL, 59),
('3a2ecbbd-0112-4c22-bde1-f8e136cf95fc', 'listening', 'Listen and select the correct word', 'perro', 'perro', ARRAY['cerdo', 'gato', 'conejo'], NULL, NULL, 60),
('3a2ecbbd-0112-4c22-bde1-f8e136cf95fc', 'word_order', 'Translate to Spanish: "The dog barks"', 'el perro ladra', 'el perro ladra', ARRAY['gato', 'maúlla', 'es'], NULL, 'Translate to Spanish', 61),
('3a2ecbbd-0112-4c22-bde1-f8e136cf95fc', 'word_order', 'Translate to Spanish: "A fast rabbit"', 'un conejo rápido', 'un conejo rápido', ARRAY['lento', 'tortuga', 'la'], NULL, 'Translate to Spanish', 62),
('3a2ecbbd-0112-4c22-bde1-f8e136cf95fc', 'word_order', 'Translate to Spanish: "My cat sleeps"', 'mi gato duerme', 'mi gato duerme', ARRAY['perro', 'jugando', 'está'], NULL, 'Translate to Spanish', 63),
('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'multiple_choice', 'How do you say "cheese" in Spanish?', 'queso', 'queso', ARRAY['pollo', 'pan', 'manzana'], NULL, NULL, 64),
('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'image_match', 'Which word represents 🍗?', 'pollo', 'pollo', ARRAY['manzana', 'carne', 'queso'], '🍗', NULL, 65),
('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'listening', 'Listen and select the correct word', 'agua', 'agua', ARRAY['leche', 'pan', 'carne'], NULL, NULL, 66),
('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'word_order', 'Translate to Spanish: "I drink water"', 'yo bebo agua', 'yo bebo agua', ARRAY['como', 'leche', 'tú'], NULL, 'Translate to Spanish', 67),
('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'word_order', 'Translate to Spanish: "I like chicken"', 'me gusta el pollo', 'me gusta el pollo', ARRAY['odio', 'pescado', 'sé'], NULL, 'Translate to Spanish', 68),
('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'word_order', 'Translate to Spanish: "A red apple"', 'una manzana roja', 'una manzana roja', ARRAY['verde', 'la', 'carne'], NULL, 'Translate to Spanish', 69),
('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a', 'multiple_choice', 'How do you say "mother" in Spanish?', 'madre', 'madre', ARRAY['padre', 'abuela', 'hermana'], NULL, NULL, 70),
('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a', 'image_match', 'Which word represents 👵?', 'abuela', 'abuela', ARRAY['tío', 'padre', 'hermana'], '👵', NULL, 71),
('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a', 'listening', 'Listen and select the correct word', 'madre', 'madre', ARRAY['abuelo', 'hermano', 'padre'], NULL, NULL, 72),
('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a', 'word_order', 'Translate to Spanish: "My little brother"', 'mi hermano pequeño', 'mi hermano pequeño', ARRAY['grande', 'hermana', 'es'], NULL, 'Translate to Spanish', 73),
('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a', 'word_order', 'Translate to Spanish: "She is my aunt"', 'ella es mi tía', 'ella es mi tía', ARRAY['él', 'tío', 'la'], NULL, 'Translate to Spanish', 74),
('0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a', 'word_order', 'Translate to Spanish: "My father works"', 'mi padre trabaja', 'mi padre trabalha', ARRAY['madre', 'durmiendo', 'está'], NULL, 'Translate to Spanish', 75),
('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'multiple_choice', 'How do you say "foot" in Spanish?', 'pie', 'pie', ARRAY['oreja', 'nariz', 'ojo'], NULL, NULL, 76),
('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'image_match', 'Which word represents 👂?', 'oreja', 'oreja', ARRAY['pie', 'pierna', 'boca'], '👂', NULL, 77),
('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'listening', 'Listen and select the correct word', 'oreja', 'oreja', ARRAY['boca', 'pierna', 'nariz'], NULL, NULL, 78),
('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'word_order', 'Translate to Spanish: "Close your eyes"', 'cierra los ojos', 'cierra los ojos', ARRAY['abre', 'boca', 'mis'], NULL, 'Translate to Spanish', 79),
('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'word_order', 'Translate to Spanish: "My two hands"', 'mis dos manos', 'mis dos manos', ARRAY['una', 'pies', 'las'], NULL, 'Translate to Spanish', 80),
('1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'word_order', 'Translate to Spanish: "I have a nose"', 'tengo una nariz', 'tengo una nariz', ARRAY['dos', 'orejas', 'tiene'], NULL, 'Translate to Spanish', 81),
('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c', 'multiple_choice', 'How do you say "car" in Spanish?', 'coche', 'coche', ARRAY['billete', 'hotel', 'autobús'], NULL, NULL, 82),
('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c', 'image_match', 'Which word represents 🚌?', 'autobús', 'autobús', ARRAY['pasaporte', 'billete', 'hotel'], '🚌', NULL, 83),
('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c', 'listening', 'Listen and select the correct word', 'avión', 'avión', ARRAY['billete', 'aeropuerto', 'coche'], NULL, NULL, 84),
('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c', 'word_order', 'Translate to Spanish: "Where is the hotel"', 'dónde está el hotel', 'dónde está el hotel', ARRAY['quién', 'aeropuerto', 'son'], NULL, 'Translate to Spanish', 85),
('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c', 'word_order', 'Translate to Spanish: "I need a ticket"', 'necesito un billete', 'necesito un billete', ARRAY['quiero', 'pasaporte', 'el'], NULL, 'Translate to Spanish', 86),
('2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c', 'word_order', 'Translate to Spanish: "The fast train"', 'el tren rápido', 'el tren rápido', ARRAY['lento', 'autobús', 'un'], NULL, 'Translate to Spanish', 87);
